// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwIS6THhUkeW26mCU5InWKtfcpgBYyuZ4',
    appId: '1:84658114900:web:0b6e15ab606ca33455b8c1',
    messagingSenderId: '84658114900',
    projectId: 'mynotes-itnsurya',
    authDomain: 'mynotes-itnsurya.firebaseapp.com',
    storageBucket: 'mynotes-itnsurya.appspot.com',
    measurementId: 'G-4LJVFGHEKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsnnzBL21hBuFsI56okKl0ENONf0zjXhQ',
    appId: '1:84658114900:android:763ec35d6cc40dcd55b8c1',
    messagingSenderId: '84658114900',
    projectId: 'mynotes-itnsurya',
    storageBucket: 'mynotes-itnsurya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0q-zqaLQxuFhB3B9RLygNvhlMQ7wBaTY',
    appId: '1:84658114900:ios:517aa0f92ed0af6255b8c1',
    messagingSenderId: '84658114900',
    projectId: 'mynotes-itnsurya',
    storageBucket: 'mynotes-itnsurya.appspot.com',
    iosBundleId: 'in.itnsurya.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0q-zqaLQxuFhB3B9RLygNvhlMQ7wBaTY',
    appId: '1:84658114900:ios:0a9b92379cb9346655b8c1',
    messagingSenderId: '84658114900',
    projectId: 'mynotes-itnsurya',
    storageBucket: 'mynotes-itnsurya.appspot.com',
    iosBundleId: 'in.itnsurya.mynotes.RunnerTests',
  );

  // static const FirebaseOptions windows = FirebaseOptions(apiKey: apiKey, appId: appId, messagingSenderId: messagingSenderId, projectId: projectId)
}
